- name: Ensure password policy is configured
  lineinfile:
    path: /etc/pam.d/common-password
    regexp: '^password.*pam_unix.so'
    line: 'password requisite pam_unix.so remember=5 minlen=12 sha512'

- name: Ensure root account is locked
  user:
    name: root
    password_lock: yes

- name: Ensure sudo requires password
  lineinfile:
    path: /etc/sudoers
    regexp: '^%sudo'
    line: '%sudo   ALL=(ALL:ALL) ALL'
    validate: '/usr/sbin/visudo -cf %s'
